# Generated by Django 5.2.6 on 2025-09-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
