# Generated by Django 5.2.6 on 2025-09-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_end_date_remove_course_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_theory', models.IntegerField(default=100)),
                ('max_practical', models.IntegerField(default=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.course')),
            ],
        ),
    ]
