# Generated by Django 5.2.6 on 2025-10-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_subjecttemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="grade",
            field=models.CharField(max_length=10),
        ),
    ]
